repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=10500']
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: sort-simple-yaml

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
